# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /run/media/abhishek/523e4673-631e-4290-8946-5b2f9a9cc817/project-dsa/DSA-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /run/media/abhishek/523e4673-631e-4290-8946-5b2f9a9cc817/project-dsa/DSA-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/abhishek/523e4673-631e-4290-8946-5b2f9a9cc817/project-dsa/DSA-Project/CMakeFiles /run/media/abhishek/523e4673-631e-4290-8946-5b2f9a9cc817/project-dsa/DSA-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /run/media/abhishek/523e4673-631e-4290-8946-5b2f9a9cc817/project-dsa/DSA-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DSA-Project

# Build rule for target.
DSA-Project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DSA-Project
.PHONY : DSA-Project

# fast build rule for target.
DSA-Project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/build
.PHONY : DSA-Project/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/main.cpp.s
.PHONY : main.cpp.s

source/graph.o: source/graph.cpp.o
.PHONY : source/graph.o

# target to build an object file
source/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/graph.cpp.o
.PHONY : source/graph.cpp.o

source/graph.i: source/graph.cpp.i
.PHONY : source/graph.i

# target to preprocess a source file
source/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/graph.cpp.i
.PHONY : source/graph.cpp.i

source/graph.s: source/graph.cpp.s
.PHONY : source/graph.s

# target to generate assembly for a file
source/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/graph.cpp.s
.PHONY : source/graph.cpp.s

source/mainmenu.o: source/mainmenu.cpp.o
.PHONY : source/mainmenu.o

# target to build an object file
source/mainmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/mainmenu.cpp.o
.PHONY : source/mainmenu.cpp.o

source/mainmenu.i: source/mainmenu.cpp.i
.PHONY : source/mainmenu.i

# target to preprocess a source file
source/mainmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/mainmenu.cpp.i
.PHONY : source/mainmenu.cpp.i

source/mainmenu.s: source/mainmenu.cpp.s
.PHONY : source/mainmenu.s

# target to generate assembly for a file
source/mainmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DSA-Project.dir/build.make CMakeFiles/DSA-Project.dir/source/mainmenu.cpp.s
.PHONY : source/mainmenu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DSA-Project"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... source/graph.o"
	@echo "... source/graph.i"
	@echo "... source/graph.s"
	@echo "... source/mainmenu.o"
	@echo "... source/mainmenu.i"
	@echo "... source/mainmenu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

